package io.openems.edge.deye.ess.charger;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
                name = "Deye hybrid DC Charger", //
                description = "Implements the DC Charger for Deye hybrid")
@interface Config {

        @AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
        String id() default "charger0";

        @AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
        String alias() default "";

        @AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
        boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
        String modbus_id() default "modbus0";

        @AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device. ")
        int modbusUnitId() default 1;

        @AttributeDefinition(name = "Maximum Active Power", description = "This is the rated output of the PV installation.")
        int maxActualPower();

        @AttributeDefinition(name = "Core target filter", description = "This is auto-generated by 'Core-ID'")
        String core_target() default "(enabled=true)";

        String webconsole_configurationFactory_nameHint() default "Deye hybrid DC Charger [{id}]";
}

